set(SRC_FILES
    App.cpp
    Object/AnimatedItems.cpp
    Object/Block.cpp
    Object/Character.cpp
    State/Menu.cpp
    State/Title.cpp
    State/Stage0.cpp
    Utility/Time.cpp
    Utility/Position.cpp
)

set(INCLUDE_FILES
    App.hpp
    State.hpp
    Object/AnimatedItems.hpp
    Object/Block.hpp
    Object/Torch.hpp
    Object/Character.hpp
    Object/ImageItems.hpp
    State/Menu.hpp
    State/Scene.hpp
    State/Title.hpp
    State/Stage0.hpp
    Utility/Time.hpp
    Utility/Position.hpp
)

set(TEST_FILES
)
